import { UserType } from '@prisma/client';

export enum Permission {
  PARCEL_CREATE = 'parcel:create',
  PARCEL_READ = 'parcel:read',
  PARCEL_UPDATE = 'parcel:update',
  PARCEL_DELETE = 'parcel:delete',
  PARCEL_MARK_DELIVERED = 'parcel:mark-delivered',
  PARCEL_NOTE_CREATE = 'parcel:note:create',
  PARCEL_NOTE_READ = 'parcel:note:read',
  PARCEL_NOTE_DELETE = 'parcel:note:delete',

  JOURNEY_CREATE = 'journey:create',
  JOURNEY_READ = 'journey:read',
  JOURNEY_UPDATE = 'journey:update',
  JOURNEY_DELETE = 'journey:delete',
  JOURNEY_NOTE_CREATE = 'journey:note:create',
  JOURNEY_NOTE_READ = 'journey:note:read',
  JOURNEY_NOTE_DELETE = 'journey:note:delete',

  COURIER_JOURNEY_CREATE = 'courier-journey:create',
  COURIER_JOURNEY_READ = 'courier-journey:read',
  COURIER_JOURNEY_UPDATE = 'courier-journey:update',
  COURIER_JOURNEY_NOTE_CREATE = 'courier-journey:note:create',
  COURIER_JOURNEY_NOTE_READ = 'courier-journey:note:read',
  COURIER_JOURNEY_NOTE_DELETE = 'courier-journey:note:delete',

  PICKUP_REQUEST_CREATE = 'pickup-request:create',
  PICKUP_REQUEST_READ = 'pickup-request:read',
  PICKUP_REQUEST_UPDATE = 'pickup-request:update',
  PICKUP_REQUEST_DELETE = 'pickup-request:delete',

  DRIVER_PROFILE_CREATE = 'driver-profile:create',
  DRIVER_PROFILE_READ = 'driver-profile:read',
  DRIVER_PROFILE_UPDATE = 'driver-profile:update',
  DRIVER_PROFILE_BLOCK = 'driver-profile:block',
  DRIVER_PROFILE_DELETE = 'driver-profile:delete',

  COURIER_PROFILE_CREATE = 'courier-profile:create',
  COURIER_PROFILE_READ = 'courier-profile:read',
  COURIER_PROFILE_UPDATE = 'courier-profile:update',
  COURIER_PROFILE_BLOCK = 'courier-profile:block',
  COURIER_PROFILE_DELETE = 'courier-profile:delete',

  CUSTOMER_CREATE = 'customer:create',
  CUSTOMER_READ = 'customer:read',
  CUSTOMER_UPDATE = 'customer:update',
  CUSTOMER_BLOCK = 'customer:block',
  CUSTOMER_DELETE = 'customer:delete',
  CUSTOMER_GRANT_ACCESS = 'customer:grant-access',
  CUSTOMER_NOTE_CREATE = 'customer:note:create',
  CUSTOMER_NOTE_READ = 'customer:note:read',
  CUSTOMER_NOTE_DELETE = 'customer:note:delete',
  CUSTOMER_ADDRESS_CREATE = 'customer:address:create',
  CUSTOMER_ADDRESS_UPDATE = 'customer:address:update',
  CUSTOMER_ADDRESS_DELETE = 'customer:address:delete',

  VEHICLE_CREATE = 'vehicle:create',
  VEHICLE_READ = 'vehicle:read',
  VEHICLE_UPDATE = 'vehicle:update',

  USER_READ = 'user:read',
  USER_DELETE = 'user:delete',

  AUDIT_READ = 'audit:read',

  APP_TABLET = 'app:tablet',
  APP_ADMIN = 'app:admin',
  APP_CUSTOMER_PORTAL = 'app:customer-portal',
}

export enum AppName {
  TABLET = 'tablet',
  ADMIN = 'admin',
  CUSTOMER_PORTAL = 'customer-portal',
}

export const APP_PERMISSION_MAP: Record<AppName, Permission> = {
  [AppName.TABLET]: Permission.APP_TABLET,
  [AppName.ADMIN]: Permission.APP_ADMIN,
  [AppName.CUSTOMER_PORTAL]: Permission.APP_CUSTOMER_PORTAL,
};

export const ROLE_PERMISSIONS: Record<UserType, Permission[]> = {
  [UserType.InternationalDriver]: [
    Permission.APP_TABLET,
    Permission.APP_ADMIN,
    Permission.APP_CUSTOMER_PORTAL,
    Permission.PARCEL_READ,
    Permission.PARCEL_MARK_DELIVERED,
    Permission.JOURNEY_READ,
    Permission.COURIER_JOURNEY_READ,
    Permission.DRIVER_PROFILE_READ,
  ],

  [UserType.ParcelCourier]: [
    Permission.APP_TABLET,
    Permission.APP_ADMIN,
    Permission.APP_CUSTOMER_PORTAL,
    Permission.PARCEL_READ,
    Permission.PARCEL_MARK_DELIVERED,
    Permission.JOURNEY_READ,
    Permission.COURIER_JOURNEY_READ,
    Permission.COURIER_JOURNEY_UPDATE,
    Permission.COURIER_PROFILE_READ,
    Permission.PICKUP_REQUEST_CREATE,
    Permission.PICKUP_REQUEST_READ,
    Permission.PICKUP_REQUEST_UPDATE,
  ],

  [UserType.Manager]: [
    Permission.APP_TABLET,
    Permission.APP_ADMIN,
    Permission.APP_CUSTOMER_PORTAL,
    Permission.PARCEL_CREATE,
    Permission.PARCEL_READ,
    Permission.PARCEL_UPDATE,
    Permission.PARCEL_NOTE_CREATE,
    Permission.PARCEL_NOTE_READ,
    Permission.PARCEL_NOTE_DELETE,
    Permission.JOURNEY_CREATE,
    Permission.JOURNEY_READ,
    Permission.JOURNEY_UPDATE,
    Permission.JOURNEY_NOTE_CREATE,
    Permission.JOURNEY_NOTE_READ,
    Permission.JOURNEY_NOTE_DELETE,
    Permission.COURIER_JOURNEY_CREATE,
    Permission.COURIER_JOURNEY_READ,
    Permission.COURIER_JOURNEY_UPDATE,
    Permission.COURIER_JOURNEY_NOTE_CREATE,
    Permission.COURIER_JOURNEY_NOTE_READ,
    Permission.COURIER_JOURNEY_NOTE_DELETE,
    Permission.PICKUP_REQUEST_CREATE,
    Permission.PICKUP_REQUEST_READ,
    Permission.PICKUP_REQUEST_UPDATE,
    Permission.PICKUP_REQUEST_DELETE,
    Permission.DRIVER_PROFILE_CREATE,
    Permission.DRIVER_PROFILE_READ,
    Permission.DRIVER_PROFILE_UPDATE,
    Permission.COURIER_PROFILE_CREATE,
    Permission.COURIER_PROFILE_READ,
    Permission.COURIER_PROFILE_UPDATE,
    Permission.CUSTOMER_CREATE,
    Permission.CUSTOMER_READ,
    Permission.CUSTOMER_UPDATE,
    Permission.CUSTOMER_NOTE_CREATE,
    Permission.CUSTOMER_NOTE_READ,
    Permission.CUSTOMER_NOTE_DELETE,
    Permission.CUSTOMER_ADDRESS_CREATE,
    Permission.CUSTOMER_ADDRESS_UPDATE,
    Permission.CUSTOMER_ADDRESS_DELETE,
    Permission.VEHICLE_READ,
    Permission.USER_READ,
    Permission.AUDIT_READ,
  ],

  [UserType.Moderator]: [
    Permission.APP_TABLET,
    Permission.APP_ADMIN,
    Permission.APP_CUSTOMER_PORTAL,
    Permission.PARCEL_CREATE,
    Permission.PARCEL_READ,
    Permission.PARCEL_UPDATE,
    Permission.PARCEL_NOTE_CREATE,
    Permission.PARCEL_NOTE_READ,
    Permission.PARCEL_NOTE_DELETE,
    Permission.JOURNEY_CREATE,
    Permission.JOURNEY_READ,
    Permission.JOURNEY_UPDATE,
    Permission.JOURNEY_NOTE_CREATE,
    Permission.JOURNEY_NOTE_READ,
    Permission.JOURNEY_NOTE_DELETE,
    Permission.COURIER_JOURNEY_CREATE,
    Permission.COURIER_JOURNEY_READ,
    Permission.COURIER_JOURNEY_UPDATE,
    Permission.COURIER_JOURNEY_NOTE_CREATE,
    Permission.COURIER_JOURNEY_NOTE_READ,
    Permission.COURIER_JOURNEY_NOTE_DELETE,
    Permission.PICKUP_REQUEST_CREATE,
    Permission.PICKUP_REQUEST_READ,
    Permission.PICKUP_REQUEST_UPDATE,
    Permission.PICKUP_REQUEST_DELETE,
    Permission.DRIVER_PROFILE_CREATE,
    Permission.DRIVER_PROFILE_READ,
    Permission.DRIVER_PROFILE_UPDATE,
    Permission.COURIER_PROFILE_CREATE,
    Permission.COURIER_PROFILE_READ,
    Permission.COURIER_PROFILE_UPDATE,
    Permission.CUSTOMER_CREATE,
    Permission.CUSTOMER_READ,
    Permission.CUSTOMER_UPDATE,
    Permission.CUSTOMER_NOTE_CREATE,
    Permission.CUSTOMER_NOTE_READ,
    Permission.CUSTOMER_NOTE_DELETE,
    Permission.CUSTOMER_ADDRESS_CREATE,
    Permission.CUSTOMER_ADDRESS_UPDATE,
    Permission.CUSTOMER_ADDRESS_DELETE,
    Permission.VEHICLE_READ,
    Permission.USER_READ,
    Permission.AUDIT_READ,
  ],

  [UserType.Customer]: [
    Permission.APP_CUSTOMER_PORTAL,
    Permission.PARCEL_READ,
    Permission.PICKUP_REQUEST_CREATE,
    Permission.PICKUP_REQUEST_READ,
    Permission.PICKUP_REQUEST_UPDATE,
    Permission.PICKUP_REQUEST_DELETE,
  ],
  [UserType.Member]: [
    Permission.APP_CUSTOMER_PORTAL,
    Permission.PARCEL_READ,
    Permission.PICKUP_REQUEST_CREATE,
    Permission.PICKUP_REQUEST_READ,
    Permission.PICKUP_REQUEST_UPDATE,
    Permission.PICKUP_REQUEST_DELETE,
  ],
  [UserType.Subscriber]: [
    Permission.APP_CUSTOMER_PORTAL,
    Permission.PARCEL_READ,
    Permission.PICKUP_REQUEST_CREATE,
    Permission.PICKUP_REQUEST_READ,
    Permission.PICKUP_REQUEST_UPDATE,
    Permission.PICKUP_REQUEST_DELETE,
  ],
};

export const ADMIN_EXTRA_PERMISSIONS: Permission[] = [
  Permission.PARCEL_DELETE,
  Permission.JOURNEY_DELETE,
  Permission.DRIVER_PROFILE_BLOCK,
  Permission.DRIVER_PROFILE_DELETE,
  Permission.COURIER_PROFILE_BLOCK,
  Permission.COURIER_PROFILE_DELETE,
  Permission.CUSTOMER_BLOCK,
  Permission.CUSTOMER_DELETE,
  Permission.CUSTOMER_GRANT_ACCESS,
  Permission.VEHICLE_CREATE,
  Permission.VEHICLE_UPDATE,
  Permission.USER_DELETE,
];
